import { USER_ROLES } from "../../common/helpers/constant.js";
import { CONTROLLERS } from "./helpers/constant.js";

export default {
  [CONTROLLERS.CREATE_VISIT]: [USER_ROLES.PATIENT],
  [CONTROLLERS.LIST_VISITS]: [USER_ROLES.FINANCE],
  [CONTROLLERS.GET_VISIT]: [
    USER_ROLES.PATIENT,
    USER_ROLES.DOCTOR,
    USER_ROLES.FINANCE,
  ],
  [CONTROLLERS.START_VISIT]: [USER_ROLES.DOCTOR],
  [CONTROLLERS.END_VISIT]: [USER_ROLES.DOCTOR],
  [CONTROLLERS.ADD_TREATMENT]: [USER_ROLES.DOCTOR],
  [CONTROLLERS.UPDATE_TREATMENT]: [USER_ROLES.DOCTOR],
  [CONTROLLERS.REMOVE_TREATMENT]: [USER_ROLES.DOCTOR],
  [CONTROLLERS.UPDATE_VISIT_NOTES]: [USER_ROLES.DOCTOR],
  [CONTROLLERS.SEARCH_VISITS]: [USER_ROLES.FINANCE],
  [CONTROLLERS.GET_DOCTOR_ACTIVE_VISIT]: [USER_ROLES.DOCTOR],
  [CONTROLLERS.GET_PATIENT_VISITS]: [
    USER_ROLES.PATIENT,
    USER_ROLES.DOCTOR,
    USER_ROLES.FINANCE,
  ],
  [CONTROLLERS.GET_DOCTOR_VISITS]: [USER_ROLES.DOCTOR, USER_ROLES.FINANCE],
};
